[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
AdaptiveOpticsProperHIL = "f8cf4d55-df09-4aa3-9f68-0fc7f08233f0"
AdaptiveOpticsSim = "002fb5eb-ad68-44a0-adbe-b299bfc2febc"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Proper = "0686a737-3bdd-44da-9bf7-6692cf630078"
SPIDERSSim = "d82bf5a6-3898-47dc-96d7-ac4be980672a"

[sources]
AdaptiveOpticsProperHIL = {path = "../../AdaptiveOpticsProperHIL.jl"}
AdaptiveOpticsSim = {path = "../../AdaptiveOpticsSim.jl"}
Proper = {path = "../../Proper.jl"}
SPIDERSSim = {path = ".."}

[compat]
AMDGPU = "2.8"
AdaptiveOpticsProperHIL = "0.1"
AdaptiveOpticsSim = "0.1"
CUDA = "6"
JSON3 = "1"
Proper = "0.3"
SPIDERSSim = "0.1"
julia = "1.12"
